name: EAS Build and Deploy

on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build for development
        if: github.ref == 'refs/heads/development'
        run: eas build --platform all --profile development --non-interactive

      - name: Build for staging
        if: github.ref == 'refs/heads/staging'
        run: eas build --platform all --profile staging --non-interactive

      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: eas build --platform all --profile production --non-interactive

      - name: Submit to stores (production only)
        if: github.ref == 'refs/heads/main'
        run: eas submit --platform all --profile production --non-interactive
